// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPkJ6IzmPZUILZME-rLHKn6HSaVDLQS10',
    appId: '1:841787590971:web:0bc60c2f5b514fd8c58f1e',
    messagingSenderId: '841787590971',
    projectId: 'card-scanner-dd716',
    authDomain: 'card-scanner-dd716.firebaseapp.com',
    storageBucket: 'card-scanner-dd716.firebasestorage.app',
    measurementId: 'G-B2DWZ7K8EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdle7T0dxu1MK8bkw5b1q-3f1gcwXBnCg',
    appId: '1:841787590971:android:d4cc88e19289cd78c58f1e',
    messagingSenderId: '841787590971',
    projectId: 'card-scanner-dd716',
    storageBucket: 'card-scanner-dd716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJcsIb_mS6_GmpkOiAqxxYKpMgnxp2cQ',
    appId: '1:841787590971:ios:69cf02c47df49e01c58f1e',
    messagingSenderId: '841787590971',
    projectId: 'card-scanner-dd716',
    storageBucket: 'card-scanner-dd716.firebasestorage.app',
    iosBundleId: 'com.example.cardScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJcsIb_mS6_GmpkOiAqxxYKpMgnxp2cQ',
    appId: '1:841787590971:ios:69cf02c47df49e01c58f1e',
    messagingSenderId: '841787590971',
    projectId: 'card-scanner-dd716',
    storageBucket: 'card-scanner-dd716.firebasestorage.app',
    iosBundleId: 'com.example.cardScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPkJ6IzmPZUILZME-rLHKn6HSaVDLQS10',
    appId: '1:841787590971:web:61497c934e9b87ebc58f1e',
    messagingSenderId: '841787590971',
    projectId: 'card-scanner-dd716',
    authDomain: 'card-scanner-dd716.firebaseapp.com',
    storageBucket: 'card-scanner-dd716.firebasestorage.app',
    measurementId: 'G-0BMWFTPT8F',
  );
}
